/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/ping': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['ping']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/openapi.yaml': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSpec']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description OIDC login kick-off (D-pp): 302 to the provider authorize endpoint with a PKCE(S256) challenge; state/nonce/verifier ride a signed HttpOnly flow cookie (600 s). returnTo may only point into /ui/ — anything else collapses to /ui/ inside the flow. OIDC unconfigured answers 500 problem+json (the dormant posture, pinned). */
    get: operations['authLogin']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description authorization-code leg (D-pp): flow cookie + state (+ iss when present) validated, code exchanged, id_token verified; then the D-tt first-login tree — bound subject logs in; else the fail-closed oidc_provisioning policy (off ⇒ deny). SUCCESS 302 to the flow returnTo with the session+CSRF cookie pair (D-qq/D-rr); DENY 302 /ui/login?error=pending for browsers or 403 problem+json for accept: application/json (same audit); validation rejections are one pinned 403. The flow cookie is always cleared. */
    get: operations['authCallback']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description revoke the CALLER's session row (audited, session_revoked) and clear both cookies (Max-Age=0). Requires a cookie session + X-CSRF-Token (D-rr — the hook answers 403 before the route); bearer actors get 400 invalid_request (a token is not a session, D-qq). */
    post: operations['authLogout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description identity echo for the SPA shell (D-zz): the caller's ActorRef — ANY authenticated actor; the global bearerAuth documents the agent leg, cookie sessions resolve through the same identity (role rides — the SPA nav and admin gate read it). NO new auth concept, reads actorCtx. */
    get: operations['authMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listTasks']
    put?: never
    post: operations['createTask']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/next': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getNextTasks']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    get: operations['getTask']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['patchTask']
    trace?: never
  }
  '/tasks/{id}/context': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    get: operations['getTaskContext']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/status': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** @description requires the current lease_token while the task is claimed (invariant 3) */
    patch: operations['changeStatus']
    trace?: never
  }
  '/tasks/{id}/split': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** @description atomic; releases any active claim and bumps the fencing generation (spec §6.2) */
    post: operations['splitTask']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/claim': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** @description atomic compare-and-swap; 409 already_claimed carries the holder's public identity */
    post: operations['claimTask']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/release': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['releaseTask']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/heartbeat': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** @description liveness record only; keepalive enforcement is deferred (spec §12) */
    post: operations['heartbeatTask']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/blocks/{blockerId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        blockerId: string
      }
      cookie?: never
    }
    get?: never
    /** @description blockerId blocks the task; 409 dependency_cycle on cycles */
    put: operations['addBlock']
    post?: never
    delete: operations['removeBlock']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/labels/{labelId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        labelId: string
      }
      cookie?: never
    }
    get?: never
    put: operations['attachLabel']
    post?: never
    delete: operations['detachLabel']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/labels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listLabels']
    put?: never
    /** @description create-or-get by name */
    post: operations['createLabel']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/audit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description append-only activity log; every authenticated actor may read everything */
    get: operations['searchAudit']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description global event feed (spec §6.8): the audit spine minus payloads (D-aa), ASCENDING from the cursor; cursor is an audit_log.id — monotonic across restarts (append-only, never purged). Tailing burns the per-actor rate-limit budget (D-dd). SSE is deferred (§6.8/§12): poll this, or register a webhook. */
    get: operations['getEvents']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/actors': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listActors']
    put?: never
    post: operations['createActor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/actors/{id}/tokens': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** @description raw_token shown exactly once; stored SHA-256 only (spec §5) */
    post: operations['createToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/tokens/{id}/revoke': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['revokeToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/policy/{key}': {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    get: operations['getPolicy']
    put: operations['setPolicy']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/allowlist': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description D-tt first-login allow-list rows (emails lowercased), emails ascending */
    get: operations['listAllowlist']
    put?: never
    /** @description add an email to the first-login allow-list (D-tt). Stored LOWERCASED; a duplicate is idempotent — 200 with the existing row (data, not error). */
    post: operations['addAllowlist']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/allowlist/{email}': {
    parameters: {
      query?: never
      header?: never
      path: {
        email: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** @description remove an entry (lowercase rule applies before lookup); absent is 404 not_found. */
    delete: operations['removeAllowlist']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/webhooks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description registered agent wake callbacks (human-only, spec §6.8); secrets are NEVER re-served after creation (D-ff) */
    get: operations['listWebhooks']
    put?: never
    /** @description register a per-agent callback (spec §6.8): HMAC secret generated and shown EXACTLY ONCE (D-ff); the delivery checkpoint anchors at the current audit watermark (D-bb) — a new webhook sees only subsequent events. url must be http(s) (use-case rule), unique (DDL rule), 8..2000 chars (schema rule). */
    post: operations['createWebhook']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/webhooks/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** @description remove a webhook; absent is 404 not_found. Delivery stops immediately. */
    delete: operations['deleteWebhook']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/webhooks/{id}/rotate-secret': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** @description new HMAC secret shown exactly once; the checkpoint RE-ANCHORS to the current watermark and the backoff clears (rotation IS re-registration, D-bb). 404 on ghost. */
    post: operations['rotateWebhookSecret']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/threads': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    /** @description threads oldest-first, each with ordered messages (spec §6.5) */
    get: operations['listThreads']
    put?: never
    /** @description kind=question requires assignee_handle and opens a review-gating question (spec §6.4.6); 409 threads_on_parent on a task with children — humans may pass ?meta_note=true (UI-only flag, audited, spec §6.2) */
    post: operations['createThread']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/threads/{tid}/messages': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        tid: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** @description reply to a thread; @handles in body route inbox entries (spec §6.5) */
    post: operations['addThreadMessage']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/threads/{tid}/answer': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        tid: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** @description appends the answer message, links it, open → answered (409 question_transition otherwise) */
    post: operations['answerQuestionThread']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/threads/{tid}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        tid: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** @description state ∈ {resolved, wont_fix} per D-n transitions; assignee_handle re-assigns (inbox) */
    patch: operations['updateQuestionThread']
    trace?: never
  }
  '/inbox': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description the caller's own inbox only, newest-first (D-r per-actor view); read-state changes are not audited — the causing action is */
    get: operations['listInbox']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/inbox/{id}/read': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** @description owner-only mark-read; absent or not-owned is 404 not_found — never 403, no existence leak (D-r) */
    post: operations['markInboxRead']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/attachments': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    /** @description list attachment metadata for a task (404 if the task does not exist) */
    get: operations['listAttachments']
    put?: never
    /** @description raw application/octet-stream body; filename/content_type via querystring; size-capped (413 payload_too_large); content-addressed, re-upload dedupes (spec §6.6) */
    post: operations['uploadAttachment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/attachments/{id}/content': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    /** @description raw bytes; HTML/SVG-origin types are downgraded to application/octet-stream with attachment disposition and nosniff (spec §10) */
    get: operations['getAttachmentContent']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/links': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    /** @description list external links for a task (404 if the task does not exist) */
    get: operations['listLinks']
    put?: never
    /** @description register an external handoff reference (D-t); insert-or-get on (task, kind, url) — re-posting the same triple returns the existing row */
    post: operations['addLink']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}/links/{linkId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        linkId: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** @description remove a link; absent or belonging to another task is 404 not_found */
    delete: operations['removeLink']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @enum {string} */
    TaskStatus: 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'done' | 'canceled'
    TaskRecord: {
      id: string
      parent_id: string | null
      title: string
      /** @description Markdown (spec §6.1) */
      description: string
      /** @description Markdown (spec §6.1) */
      acceptance_criteria: string
      status: components['schemas']['TaskStatus']
      blocked_flag: boolean
      assignee_id: string | null
      position: number
      created_by: string
      created_at: string
      updated_at: string
      claim_token_id: string | null
      claim_generation: number
      last_heartbeat_at: string | null
    }
    /** @description flat task DTO — the row plus its rollup counts and label names (toTaskDto) */
    Task: components['schemas']['TaskRecord'] & {
      child_count?: number
      unmet_blockers?: number
      labels?: string[]
    }
    TaskWithCounts: {
      task?: components['schemas']['TaskRecord']
      child_count?: number
      unmet_blockers?: number
      labels?: string[]
    }
    ContextBundle: {
      task?: components['schemas']['TaskRecord']
      child_count?: number
      unmet_blockers?: number
      ancestors?: {
        id?: string
        title?: string
        status?: components['schemas']['TaskStatus']
        acceptance_criteria?: string
      }[]
      blockers?: {
        id?: string
        title?: string
        status?: components['schemas']['TaskStatus']
      }[]
      labels?: components['schemas']['Label'][]
      /** @description open questions on the task (D-n/D-m); first-message text preview */
      open_questions?: {
        id?: string
        /** @enum {string} */
        state?: 'open' | 'answered' | 'resolved' | 'wont_fix'
        assignee_handle?: string
        question?: string
      }[]
      links?: components['schemas']['Link'][]
      attachments?: components['schemas']['Attachment'][]
    }
    Label: {
      id?: string
      name?: string
      color?: string
      created_at?: string
    }
    Actor: {
      id?: string
      /** @enum {string} */
      kind?: 'human' | 'agent'
      /** @enum {string|null} */
      role?: 'admin' | 'member' | null
      /** @description internal OIDC subject binding; admin-visible */
      oidc_subject?: string | null
      handle?: string
      display_name?: string
      description?: string
      created_at?: string
    }
    AllowlistEntry: {
      email?: string
      added_by?: string
      created_at?: string
    }
    AuditEntry: {
      id?: number
      actor_id?: string | null
      token_id?: string | null
      action?: string
      entity_type?: string
      entity_id?: string
      before?: unknown
      after?: unknown
      reason?: string | null
      created_at?: string
    }
    /** @description audit spine minus payloads (D-aa) — before/after snapshots are excluded; the machine reason rides */
    Event: {
      /** @description audit_log.id — the restart-monotonic cursor */
      cursor?: number
      actor_id?: string | null
      token_id?: string | null
      action?: string
      entity_type?: string
      entity_id?: string
      reason?: string | null
      created_at?: string
    }
    /** @description RFC 9457; `already_claimed` additionally carries holder_handle/holder_display_name */
    Problem: {
      type: string
      title: string
      status: number
      /** @enum {string} */
      code:
        | 'not_found'
        | 'forbidden'
        | 'unauthenticated'
        | 'invalid_request'
        | 'internal_error'
        | 'handle_taken'
        | 'already_claimed'
        | 'not_a_leaf'
        | 'open_descendants'
        | 'canceled_terminal'
        | 'stale_lease'
        | 'dependency_cycle'
        | 'agent_close_forbidden'
        | 'open_questions'
        | 'threads_on_parent'
        | 'question_transition'
        | 'rate_limited'
        | 'idempotency_in_flight'
        | 'payload_too_large'
        | 'unsupported_media_type'
      detail?: string
    }
    /** @description thread row (ports.ts ThreadRecord); question fields NULL for notes (D-m) */
    Thread: {
      id?: string
      task_id?: string
      /** @enum {string} */
      kind?: 'note' | 'question'
      /** @enum {string|null} */
      state?: 'open' | 'answered' | 'resolved' | 'wont_fix' | null
      assignee_id?: string | null
      answer_message_id?: string | null
      created_by?: string
      created_at?: string
      updated_at?: string
    }
    Message: {
      id?: string
      thread_id?: string
      seq?: number
      author_id?: string
      body?: string
      created_at?: string
    }
    /** @description thread + its messages ordered by seq (spec §6.5) */
    ThreadWithMessages: {
      thread?: components['schemas']['Thread']
      messages?: components['schemas']['Message'][]
    }
    /** @description inbox entry (ports.ts InboxItemRecord); kind vocabulary mirrors domain INBOX_ITEM_KINDS (D-r, extended by D-cc in Plan C: claim_conflict rides the webhook wake path) */
    InboxItem: {
      id?: string
      actor_id?: string
      /** @enum {string} */
      kind?: 'assigned' | 'mentioned' | 'question_assigned' | 'claim_conflict'
      task_id?: string
      thread_id?: string | null
      read?: boolean
      created_at?: string
    }
    /** @description external link on a task (ports.ts LinkRecord, D-t) */
    Link: {
      id?: string
      task_id?: string
      /** @enum {string} */
      kind?: 'pr' | 'commit' | 'doc' | 'other'
      url?: string
      created_by?: string
      created_at?: string
    }
    /** @description content-addressed attachment metadata (ports.ts AttachmentRecord, D-s); bytes of the stored blob */
    Attachment: {
      id?: string
      task_id?: string
      filename?: string
      content_type?: string
      sha256?: string
      bytes?: number
      created_by?: string
      created_at?: string
    }
    /** @description registered callback (ports.ts WebhookRecord, D-bb); secret exists only in create/rotate responses (D-ff) */
    Webhook: {
      id?: string
      actor_id?: string
      url?: string
      created_by?: string
      created_at?: string
      /** @description audit id the loop delivers AFTER (D-bb) */
      delivered_cursor?: number
    }
    /** @description webhook row + the secret, returned exactly once (D-ff, spec §5 raw_token lineage) */
    WebhookWithSecret: components['schemas']['Webhook'] & {
      /** @description base64url 32-byte HMAC key; signs X-Nightshift-Signature (D-bb) */
      secret?: string
    }
  }
  responses: {
    /** @description domain rejection — stable machine code, branch on it (spec §11) */
    Problem: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['Problem']
      }
    }
  }
  parameters: {
    TaskId: string
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  ping: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description liveness */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            pong?: string
          }
        }
      }
    }
  }
  getSpec: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description This contract */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/yaml': string
        }
      }
    }
  }
  authLogin: {
    parameters: {
      query?: {
        returnTo?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description redirect to the provider authorize URL */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  authCallback: {
    parameters: {
      query?: {
        code?: string
        state?: string
        iss?: string
        error?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description login success (returnTo) or browser deny (/ui/login?error=…) */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  authLogout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description revoked (no body; both cookies cleared) */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  authMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description the caller's ActorRef */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            id?: string
            /** @enum {string} */
            kind?: 'human' | 'agent'
            /** @enum {string|null} */
            role?: 'admin' | 'member' | null
            handle?: string
            display_name?: string
          }
        }
      }
      default: components['responses']['Problem']
    }
  }
  listTasks: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description every task with rollup counts */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Task'][]
        }
      }
    }
  }
  createTask: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          title: string
          description?: string
          acceptance_criteria?: string
          parent_id?: string
          status?: components['schemas']['TaskStatus']
          labels?: string[]
        }
      }
    }
    responses: {
      /** @description created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Task']
        }
      }
      default: components['responses']['Problem']
    }
  }
  getNextTasks: {
    parameters: {
      query?: {
        label?: string
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description ready leaves (spec §6.3) */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Task'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  getTask: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description task */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Task']
        }
      }
      default: components['responses']['Problem']
    }
  }
  patchTask: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          title?: string
          description?: string
          acceptance_criteria?: string
          blocked_flag?: boolean
          assignee_id?: string | null
        }
      }
    }
    responses: {
      /** @description updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Task']
        }
      }
      default: components['responses']['Problem']
    }
  }
  getTaskContext: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description one-call context bundle (spec §7.2) — questions, links and attachments populated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContextBundle']
        }
      }
      default: components['responses']['Problem']
    }
  }
  changeStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          status: components['schemas']['TaskStatus']
          reason: string
          lease_token?: string
        }
      }
    }
    responses: {
      /** @description new task state */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Task']
        }
      }
      default: components['responses']['Problem']
    }
  }
  splitTask: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          children: {
            title: string
            /** @description Markdown (spec §6.1) */
            description?: string
            /** @description Markdown (spec §6.1) */
            acceptance_criteria?: string
            status?: components['schemas']['TaskStatus']
          }[]
        }
      }
    }
    responses: {
      /** @description children created; see TaskWithCounts for the parent/created shape asymmetry */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            parent?: components['schemas']['TaskWithCounts']
            created?: components['schemas']['TaskRecord'][]
          }
        }
      }
      default: components['responses']['Problem']
    }
  }
  claimTask: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description claimed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            lease_token?: string
            generation?: number
          }
        }
      }
      default: components['responses']['Problem']
    }
  }
  releaseTask: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description released */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Task']
        }
      }
      default: components['responses']['Problem']
    }
  }
  heartbeatTask: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          lease_token: string
        }
      }
    }
    responses: {
      /** @description liveness recorded */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Task']
        }
      }
      default: components['responses']['Problem']
    }
  }
  addBlock: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        blockerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description edge present */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  removeBlock: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        blockerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description edge absent */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  attachLabel: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        labelId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description attached */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  detachLabel: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        labelId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description detached */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  listLabels: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description all labels */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Label'][]
        }
      }
    }
  }
  createLabel: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          name: string
          color?: string
        }
      }
    }
    responses: {
      /** @description label */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Label']
        }
      }
      default: components['responses']['Problem']
    }
  }
  searchAudit: {
    parameters: {
      query?: {
        entity_type?: string
        entity_id?: string
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description newest first */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuditEntry'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  getEvents: {
    parameters: {
      query?: {
        cursor?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description events with cursor strictly increasing; empty when caught up */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Event'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  listActors: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description all actors */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Actor'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  createActor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          kind: 'human' | 'agent'
          handle: string
          display_name: string
          description?: string
          /** @enum {string} */
          role?: 'admin' | 'member'
        }
      }
    }
    responses: {
      /** @description created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Actor']
        }
      }
      default: components['responses']['Problem']
    }
  }
  createToken: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          label: string
        }
      }
    }
    responses: {
      /** @description issued */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            token_id?: string
            actor_id?: string
            label?: string
            created_at?: string
            raw_token?: string
          }
        }
      }
      default: components['responses']['Problem']
    }
  }
  revokeToken: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description revoked */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  getPolicy: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description policy value (allowlisted keys) */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            key?: string
            value?: string | null
          }
        }
      }
      default: components['responses']['Problem']
    }
  }
  setPolicy: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          value: 'on' | 'off' | 'allowlist'
        }
      }
    }
    responses: {
      /** @description stored */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            key?: string
            value?: string
          }
        }
      }
      default: components['responses']['Problem']
    }
  }
  listAllowlist: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description allow-list entries */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AllowlistEntry'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  addAllowlist: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          email: string
        }
      }
    }
    responses: {
      /** @description already present — the existing row (idempotent, D-tt) */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AllowlistEntry']
        }
      }
      /** @description created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AllowlistEntry']
        }
      }
      default: components['responses']['Problem']
    }
  }
  removeAllowlist: {
    parameters: {
      query?: never
      header?: never
      path: {
        email: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description removed (no body) */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  listWebhooks: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description webhook rows, oldest first */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Webhook'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  createWebhook: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          agent_id: string
          url: string
        }
      }
    }
    responses: {
      /** @description webhook row + the one-time secret */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WebhookWithSecret']
        }
      }
      default: components['responses']['Problem']
    }
  }
  deleteWebhook: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description removed (no body) */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  rotateWebhookSecret: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description webhook row + the new one-time secret */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WebhookWithSecret']
        }
      }
      default: components['responses']['Problem']
    }
  }
  listThreads: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description thread list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ThreadWithMessages'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  createThread: {
    parameters: {
      query?: {
        meta_note?: boolean
      }
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          kind: 'note' | 'question'
          body: string
          assignee_handle?: string
        }
      }
    }
    responses: {
      /** @description thread with its first message (CreateThreadResult, ports.ts) */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            thread?: components['schemas']['Thread']
            message?: components['schemas']['Message']
          }
        }
      }
      default: components['responses']['Problem']
    }
  }
  addThreadMessage: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        tid: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          body: string
        }
      }
    }
    responses: {
      /** @description appended message */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Message']
        }
      }
      default: components['responses']['Problem']
    }
  }
  answerQuestionThread: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        tid: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          body: string
        }
      }
    }
    responses: {
      /** @description answer + updated thread */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message?: components['schemas']['Message']
            thread?: components['schemas']['Thread']
          }
        }
      }
      default: components['responses']['Problem']
    }
  }
  updateQuestionThread: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        tid: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          state?: 'open' | 'answered' | 'resolved' | 'wont_fix'
          assignee_handle?: string
        }
      }
    }
    responses: {
      /** @description updated thread */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Thread']
        }
      }
      default: components['responses']['Problem']
    }
  }
  listInbox: {
    parameters: {
      query?: {
        unread_only?: boolean
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description inbox items */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InboxItem'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  markInboxRead: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description marked read (no body) */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
  listAttachments: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description metadata rows, oldest first */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Attachment'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  uploadAttachment: {
    parameters: {
      query: {
        filename: string
        content_type?: string
      }
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/octet-stream': string
      }
    }
    responses: {
      /** @description stored attachment metadata */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Attachment']
        }
      }
      default: components['responses']['Problem']
    }
  }
  getAttachmentContent: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description the stored bytes */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/octet-stream': string
        }
      }
      default: components['responses']['Problem']
    }
  }
  listLinks: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description link rows, oldest first */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Link'][]
        }
      }
      default: components['responses']['Problem']
    }
  }
  addLink: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          kind: 'pr' | 'commit' | 'doc' | 'other'
          url: string
        }
      }
    }
    responses: {
      /** @description the link row (existing or newly created) */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Link']
        }
      }
      default: components['responses']['Problem']
    }
  }
  removeLink: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['TaskId']
        linkId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description removed (no body) */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      default: components['responses']['Problem']
    }
  }
}
